version: "3.9"
services:
  react-backend:
    build: .
    ports:
      - 7070:3030
    volumes:
      - .:/app
    depends_on: # 이하의 컨테이너들을 먼저 실행
      - react-db
  react-db:
    platform: linux/x86_64 # M1チップ対応のため追記
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gwak
      MYSQL_USER: ghw
      MYSQL_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
